# Generated by Django 4.2.16 on 2025-02-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jennifer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
